.build: &build-def
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    EXTRA_TAGS: ""
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
  script:
    - docker build --build-arg PHP_VERSION=${PHP_VERSION} --build-arg UNIT_VERSION=${UNIT_VERSION} -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --network host --no-cache -f Dockerfile .
    - TAGS="${PHP_VERSION}-${UNIT_VERSION:1:2} ${EXTRA_TAGS}"
    - for tag in ${TAGS}; do docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} jitesoft/phpunit:${tag}; docker push jitesoft/phpunit:${tag}; done
  after_script:
    - docker run --rm ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} phpunit --version
    - docker run --rm ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} composer -V
    - docker run --rm ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} php -v

build:7.3:7:
  <<: *build-def
  variables:
    EXTRA_TAGS: "latest stable"
    PHP_VERSION: "7.3"
    UNIT_VERSION: "^7"

build:7.2:7:
    <<: *build-def
    variables:
      PHP_VERSION: "7.2"
      UNIT_VERSION: "^7"

build:7.1:7:
    <<: *build-def
    variables:
      PHP_VERSION: "7.1"
      UNIT_VERSION: "^7"

build:7.2:6:
    <<: *build-def
    variables:
      PHP_VERSION: "7.2"
      UNIT_VERSION: "^6"

build:7.1:6:
    <<: *build-def
    variables:
      PHP_VERSION: "7.1"
      UNIT_VERSION: "^6"

build:7.0:6:
    <<: *build-def
    variables:
      PHP_VERSION: "7.0"
      UNIT_VERSION: "^6"
