.build: &build-def
  stage: deploy
  image: docker:latest
  variables:
    EXTRA_TAGS: ""
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
  script:
    - docker pull jitesoft/composer:${PHP_VERSION}
    - BUILD=$(docker build --build-arg PHP_VERSION=${PHP_VERSION} --build-arg UNIT_VERSION=${UNIT_VERSION} --no-cache -q -f Dockerfile .)
    - TAGS="${PHP_VERSION}-${UNIT_VERSION:1:2} ${EXTRA_TAGS}"
    - for tag in ${TAGS}; do docker tag ${BUILD} jitesoft/phpunit:${tag}; docker push jitesoft/phpunit:${tag}; done
  after_script:
    - docker run --rm jitesoft/phpunit:${PHP_VERSION}-${UNIT_VERSION:1:2} phpunit --version
    - docker run --rm jitesoft/phpunit:${PHP_VERSION}-${UNIT_VERSION:1:2} composer -V
    - docker run --rm jitesoft/phpunit:${PHP_VERSION}-${UNIT_VERSION:1:2} php -v

build:7.2:7:
    <<: *build-def
    variables:
      EXTRA_TAGS: "latest stable"
      PHP_VERSION: "7.2"
      UNIT_VERSION: "^7"

build:7.1:7:
    <<: *build-def
    variables:
      PHP_VERSION: "7.1"
      UNIT_VERSION: "^7"

build:7.2:6:
    <<: *build-def
    variables:
      PHP_VERSION: "7.2"
      UNIT_VERSION: "^6"

build:7.1:6:
    <<: *build-def
    variables:
      PHP_VERSION: "7.1"
      UNIT_VERSION: "^6"

build:7.0:6:
    <<: *build-def
    variables:
      PHP_VERSION: "7.0"
      UNIT_VERSION: "^6"
